# Generated by Django 5.1.4 on 2024-12-31 10:32

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_project_owner_alter_task_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="document",
            field=models.FileField(blank=True, upload_to=api.utils.file_uploder),
        ),
    ]
